<?php
class AdminLevelConfig {
	public static $ADMINLEVELS = array(
		'Master' => array(
			'adminlevel' => array(
				'type' => 'SuperAdmin',
			),
			'access' => array(
				'server_options' => true,
				'game_infos' => true,
				'chat' => true,
				'maps_list' => true,
				'maps_local' => true,
				'maps_upload' => true,
				'maps_order' => true,
				'maps_matchsettings' => true,
				'maps_create_matchsettings' => true,
				'link_access_server' => true,
				'plugins_list' => true,
				'guest_ban' => true,
			),
			'permission' => array(
				'speed_admin' => true,
				'switch_server' => true,
				'player_kick' => true,
				'player_ban' => true,
				'player_guest' => true,
				'player_ignore' => true,
				'player_forcetospectator' => true,
				'player_forcetoplayer' => true,
				'player_changeteam' => true,
				'force_scores' => true,
				'cancel_vote' => true,
				'srvopts_general_name' => true,
				'srvopts_general_comment' => true,
				'srvopts_general_playerpassword' => true,
				'srvopts_general_spectatorpassword' => true,
				'srvopts_general_nbplayers' => true,
				'srvopts_general_nbspectators' => true,
				'srvopts_advanced' => true,
				'srvopts_adminlevelpassword' => true,
				'srvopts_importexport' => true,
				'gameinfos_general_gamemode' => true,
				'gameinfos_general_options' => true,
				'gameinfos_general_warmup' => true,
				'gameinfos_teams_options' => true,
				'gameinfos_gamemode_options' => true,
				'chat_sendmessage' => true,
				'maps_list_moveaftercurrent' => true,
				'maps_list_removetolist' => true,
				'maps_local_add' => true,
				'maps_local_insert' => true,
				'maps_local_download' => true,
				'maps_local_rename' => true,
				'maps_local_move' => true,
				'maps_local_delete' => true,
				'maps_upload_add' => true,
				'maps_upload_insert' => true,
				'maps_upload_folder' => true,
				'maps_matchsettings_save' => true,
				'maps_matchsettings_load' => true,
				'maps_matchsettings_add' => true,
				'maps_matchsettings_insert' => true,
				'maps_matchsettings_edit' => true,
				'maps_matchsettings_delete' => true,
				'folder_new' => true,
				'folder_rename' => true,
				'folder_move' => true,
				'folder_delete' => true,
				'guestban_addplayer' => true,
				'guestban_removeplayer' => true,
				'guestban_playlist_new' => true,
				'guestban_playlist_save' => true,
				'guestban_playlist_load' => true,
				'guestban_playlist_delete' => true,
			)
		),
		'Team' => array(
			'adminlevel' => array(
				'type' => 'Admin',
			),
			'access' => array(
				'server_options' => true,
				'game_infos' => true,
				'chat' => true,
				'maps_list' => true,
				'maps_local' => true,
				'maps_upload' => true,
				'maps_order' => true,
				'maps_matchsettings' => true,
				'maps_create_matchsettings' => true,
				'link_access_server' => true,
				'plugins_list' => true,
				'guest_ban' => true,
			),
			'permission' => array(
				'speed_admin' => true,
				'switch_server' => true,
				'player_kick' => true,
				'player_ban' => true,
				'player_guest' => true,
				'player_ignore' => true,
				'player_forcetospectator' => true,
				'player_forcetoplayer' => true,
				'player_changeteam' => true,
				'force_scores' => true,
				'cancel_vote' => true,
				'srvopts_general_name' => true,
				'srvopts_general_comment' => true,
				'srvopts_general_playerpassword' => true,
				'srvopts_general_spectatorpassword' => true,
				'srvopts_general_nbplayers' => true,
				'srvopts_general_nbspectators' => true,
				'srvopts_advanced' => false,
				'srvopts_adminlevelpassword' => false,
				'srvopts_importexport' => false,
				'gameinfos_general_gamemode' => true,
				'gameinfos_general_options' => false,
				'gameinfos_general_warmup' => true,
				'gameinfos_teams_options' => true,
				'gameinfos_gamemode_options' => true,
				'chat_sendmessage' => true,
				'maps_list_moveaftercurrent' => true,
				'maps_list_removetolist' => true,
				'maps_local_add' => true,
				'maps_local_insert' => true,
				'maps_local_download' => true,
				'maps_local_rename' => true,
				'maps_local_move' => true,
				'maps_local_delete' => false,
				'maps_upload_add' => true,
				'maps_upload_insert' => true,
				'maps_upload_folder' => true,
				'maps_matchsettings_save' => true,
				'maps_matchsettings_load' => true,
				'maps_matchsettings_add' => true,
				'maps_matchsettings_insert' => true,
				'maps_matchsettings_edit' => true,
				'maps_matchsettings_delete' => false,
				'folder_new' => true,
				'folder_rename' => true,
				'folder_move' => true,
				'folder_delete' => false,
				'guestban_addplayer' => true,
				'guestban_removeplayer' => true,
				'guestban_playlist_new' => true,
				'guestban_playlist_save' => true,
				'guestban_playlist_load' => true,
				'guestban_playlist_delete' => false,
			)
		),
		'Public' => array(
			'adminlevel' => array(
				'type' => 'User',
			),
			'access' => array(
				'chat' => true,
				'maps_list' => true,
				'link_access_server' => true,
			),
			'permission' => array()
		)
	);
}
?>